--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/project/my_project/I___Anlogic____hdmi_transmitter_over_serdes_demo____PH400/user_source/hdl_source/HDMI_Transmitter/HDMI_EDID/Stream_to_IIC_Master_Phy/w10_d1024_fifo.vhd
 -- Date	:	2022 03 03
 -- TD version	:	5.5.45522
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_v2_macro;
	USE ph1_v2_macro.PH1_COMPONENTS.all;

ENTITY w11_d1024_fifo IS
PORT (
	di	: IN STD_LOGIC_VECTOR(10 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	dout	: OUT STD_LOGIC_VECTOR(10 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(10 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(10 DOWNTO 0)
	);
END w11_d1024_fifo;

ARCHITECTURE struct OF w11_d1024_fifo IS

	BEGIN
	inst : PH1_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 11,
			ADDR_WIDTH			=> 10,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"20K"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			dout	=> dout,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
