/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/project/my_project/I___Anlogic____hdmi_transmitter_over_serdes_demo____PH400/user_source/hdl_source/HDMI_Transmitter/HDMI_EDID/Stream_to_IIC_Master_Phy/w10_d1024_fifo.v
 ** Date	:	2022 03 03
 ** TD version	:	5.5.45522
\************************************************************/

`timescale 1ns / 1ps

module w11_d1024_fifo (
	rst,
	di, re, clk, we,
	dout,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [10:0] di;
	input clk, we;
	input re;

	output [10:0] dout;
	output empty_flag;
	output full_flag;
	output [10:0] rdusedw;
	output [10:0] wrusedw;

DR1_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(11),
	.ADDR_WIDTH(10),
	.SHOWAHEAD(0),
	.IMPLEMENT("20K")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.dout(dout),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule